// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: execution_statistics.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_execution_5fstatistics_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_execution_5fstatistics_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_execution_5fstatistics_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_execution_5fstatistics_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
namespace tools {
namespace protos {
class ExecutionStatistics;
class ExecutionStatisticsDefaultTypeInternal;
extern ExecutionStatisticsDefaultTypeInternal _ExecutionStatistics_default_instance_;
class ResourceUsage;
class ResourceUsageDefaultTypeInternal;
extern ResourceUsageDefaultTypeInternal _ResourceUsage_default_instance_;
}  // namespace protos
}  // namespace tools
PROTOBUF_NAMESPACE_OPEN
template<> ::tools::protos::ExecutionStatistics* Arena::CreateMaybeMessage<::tools::protos::ExecutionStatistics>(Arena*);
template<> ::tools::protos::ResourceUsage* Arena::CreateMaybeMessage<::tools::protos::ResourceUsage>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace tools {
namespace protos {

// ===================================================================

class ResourceUsage PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:tools.protos.ResourceUsage) */ {
 public:
  inline ResourceUsage() : ResourceUsage(nullptr) {};
  virtual ~ResourceUsage();

  ResourceUsage(const ResourceUsage& from);
  ResourceUsage(ResourceUsage&& from) noexcept
    : ResourceUsage() {
    *this = ::std::move(from);
  }

  inline ResourceUsage& operator=(const ResourceUsage& from) {
    CopyFrom(from);
    return *this;
  }
  inline ResourceUsage& operator=(ResourceUsage&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ResourceUsage& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ResourceUsage* internal_default_instance() {
    return reinterpret_cast<const ResourceUsage*>(
               &_ResourceUsage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ResourceUsage& a, ResourceUsage& b) {
    a.Swap(&b);
  }
  inline void Swap(ResourceUsage* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ResourceUsage* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ResourceUsage* New() const final {
    return CreateMaybeMessage<ResourceUsage>(nullptr);
  }

  ResourceUsage* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ResourceUsage>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)
    final;
  void CopyFrom(const ResourceUsage& from);
  void MergeFrom(const ResourceUsage& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ResourceUsage* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "tools.protos.ResourceUsage";
  }
  protected:
  explicit ResourceUsage(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUtimeSecFieldNumber = 1,
    kUtimeUsecFieldNumber = 2,
    kStimeSecFieldNumber = 3,
    kStimeUsecFieldNumber = 4,
    kMaxrssFieldNumber = 5,
    kIxrssFieldNumber = 6,
    kIdrssFieldNumber = 7,
    kIsrssFieldNumber = 8,
    kMinfltFieldNumber = 9,
    kMajfltFieldNumber = 10,
    kNswapFieldNumber = 11,
    kInblockFieldNumber = 12,
    kOublockFieldNumber = 13,
    kMsgsndFieldNumber = 14,
    kMsgrcvFieldNumber = 15,
    kNsignalsFieldNumber = 16,
    kNvcswFieldNumber = 17,
    kNivcswFieldNumber = 18,
  };
  // int64 utime_sec = 1;
  void clear_utime_sec();
  ::PROTOBUF_NAMESPACE_ID::int64 utime_sec() const;
  void set_utime_sec(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_utime_sec() const;
  void _internal_set_utime_sec(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // int64 utime_usec = 2;
  void clear_utime_usec();
  ::PROTOBUF_NAMESPACE_ID::int64 utime_usec() const;
  void set_utime_usec(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_utime_usec() const;
  void _internal_set_utime_usec(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // int64 stime_sec = 3;
  void clear_stime_sec();
  ::PROTOBUF_NAMESPACE_ID::int64 stime_sec() const;
  void set_stime_sec(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_stime_sec() const;
  void _internal_set_stime_sec(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // int64 stime_usec = 4;
  void clear_stime_usec();
  ::PROTOBUF_NAMESPACE_ID::int64 stime_usec() const;
  void set_stime_usec(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_stime_usec() const;
  void _internal_set_stime_usec(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // int64 maxrss = 5;
  void clear_maxrss();
  ::PROTOBUF_NAMESPACE_ID::int64 maxrss() const;
  void set_maxrss(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_maxrss() const;
  void _internal_set_maxrss(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // int64 ixrss = 6;
  void clear_ixrss();
  ::PROTOBUF_NAMESPACE_ID::int64 ixrss() const;
  void set_ixrss(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_ixrss() const;
  void _internal_set_ixrss(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // int64 idrss = 7;
  void clear_idrss();
  ::PROTOBUF_NAMESPACE_ID::int64 idrss() const;
  void set_idrss(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_idrss() const;
  void _internal_set_idrss(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // int64 isrss = 8;
  void clear_isrss();
  ::PROTOBUF_NAMESPACE_ID::int64 isrss() const;
  void set_isrss(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_isrss() const;
  void _internal_set_isrss(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // int64 minflt = 9;
  void clear_minflt();
  ::PROTOBUF_NAMESPACE_ID::int64 minflt() const;
  void set_minflt(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_minflt() const;
  void _internal_set_minflt(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // int64 majflt = 10;
  void clear_majflt();
  ::PROTOBUF_NAMESPACE_ID::int64 majflt() const;
  void set_majflt(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_majflt() const;
  void _internal_set_majflt(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // int64 nswap = 11;
  void clear_nswap();
  ::PROTOBUF_NAMESPACE_ID::int64 nswap() const;
  void set_nswap(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_nswap() const;
  void _internal_set_nswap(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // int64 inblock = 12;
  void clear_inblock();
  ::PROTOBUF_NAMESPACE_ID::int64 inblock() const;
  void set_inblock(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_inblock() const;
  void _internal_set_inblock(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // int64 oublock = 13;
  void clear_oublock();
  ::PROTOBUF_NAMESPACE_ID::int64 oublock() const;
  void set_oublock(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_oublock() const;
  void _internal_set_oublock(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // int64 msgsnd = 14;
  void clear_msgsnd();
  ::PROTOBUF_NAMESPACE_ID::int64 msgsnd() const;
  void set_msgsnd(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_msgsnd() const;
  void _internal_set_msgsnd(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // int64 msgrcv = 15;
  void clear_msgrcv();
  ::PROTOBUF_NAMESPACE_ID::int64 msgrcv() const;
  void set_msgrcv(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_msgrcv() const;
  void _internal_set_msgrcv(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // int64 nsignals = 16;
  void clear_nsignals();
  ::PROTOBUF_NAMESPACE_ID::int64 nsignals() const;
  void set_nsignals(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_nsignals() const;
  void _internal_set_nsignals(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // int64 nvcsw = 17;
  void clear_nvcsw();
  ::PROTOBUF_NAMESPACE_ID::int64 nvcsw() const;
  void set_nvcsw(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_nvcsw() const;
  void _internal_set_nvcsw(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // int64 nivcsw = 18;
  void clear_nivcsw();
  ::PROTOBUF_NAMESPACE_ID::int64 nivcsw() const;
  void set_nivcsw(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_nivcsw() const;
  void _internal_set_nivcsw(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // @@protoc_insertion_point(class_scope:tools.protos.ResourceUsage)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::int64 utime_sec_;
  ::PROTOBUF_NAMESPACE_ID::int64 utime_usec_;
  ::PROTOBUF_NAMESPACE_ID::int64 stime_sec_;
  ::PROTOBUF_NAMESPACE_ID::int64 stime_usec_;
  ::PROTOBUF_NAMESPACE_ID::int64 maxrss_;
  ::PROTOBUF_NAMESPACE_ID::int64 ixrss_;
  ::PROTOBUF_NAMESPACE_ID::int64 idrss_;
  ::PROTOBUF_NAMESPACE_ID::int64 isrss_;
  ::PROTOBUF_NAMESPACE_ID::int64 minflt_;
  ::PROTOBUF_NAMESPACE_ID::int64 majflt_;
  ::PROTOBUF_NAMESPACE_ID::int64 nswap_;
  ::PROTOBUF_NAMESPACE_ID::int64 inblock_;
  ::PROTOBUF_NAMESPACE_ID::int64 oublock_;
  ::PROTOBUF_NAMESPACE_ID::int64 msgsnd_;
  ::PROTOBUF_NAMESPACE_ID::int64 msgrcv_;
  ::PROTOBUF_NAMESPACE_ID::int64 nsignals_;
  ::PROTOBUF_NAMESPACE_ID::int64 nvcsw_;
  ::PROTOBUF_NAMESPACE_ID::int64 nivcsw_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_execution_5fstatistics_2eproto;
};
// -------------------------------------------------------------------

class ExecutionStatistics PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:tools.protos.ExecutionStatistics) */ {
 public:
  inline ExecutionStatistics() : ExecutionStatistics(nullptr) {};
  virtual ~ExecutionStatistics();

  ExecutionStatistics(const ExecutionStatistics& from);
  ExecutionStatistics(ExecutionStatistics&& from) noexcept
    : ExecutionStatistics() {
    *this = ::std::move(from);
  }

  inline ExecutionStatistics& operator=(const ExecutionStatistics& from) {
    CopyFrom(from);
    return *this;
  }
  inline ExecutionStatistics& operator=(ExecutionStatistics&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ExecutionStatistics& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ExecutionStatistics* internal_default_instance() {
    return reinterpret_cast<const ExecutionStatistics*>(
               &_ExecutionStatistics_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ExecutionStatistics& a, ExecutionStatistics& b) {
    a.Swap(&b);
  }
  inline void Swap(ExecutionStatistics* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ExecutionStatistics* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ExecutionStatistics* New() const final {
    return CreateMaybeMessage<ExecutionStatistics>(nullptr);
  }

  ExecutionStatistics* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ExecutionStatistics>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)
    final;
  void CopyFrom(const ExecutionStatistics& from);
  void MergeFrom(const ExecutionStatistics& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ExecutionStatistics* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "tools.protos.ExecutionStatistics";
  }
  protected:
  explicit ExecutionStatistics(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kResourceUsageFieldNumber = 1,
  };
  // .tools.protos.ResourceUsage resource_usage = 1;
  bool has_resource_usage() const;
  private:
  bool _internal_has_resource_usage() const;
  public:
  void clear_resource_usage();
  const ::tools::protos::ResourceUsage& resource_usage() const;
  ::tools::protos::ResourceUsage* release_resource_usage();
  ::tools::protos::ResourceUsage* mutable_resource_usage();
  void set_allocated_resource_usage(::tools::protos::ResourceUsage* resource_usage);
  private:
  const ::tools::protos::ResourceUsage& _internal_resource_usage() const;
  ::tools::protos::ResourceUsage* _internal_mutable_resource_usage();
  public:
  void unsafe_arena_set_allocated_resource_usage(
      ::tools::protos::ResourceUsage* resource_usage);
  ::tools::protos::ResourceUsage* unsafe_arena_release_resource_usage();

  // @@protoc_insertion_point(class_scope:tools.protos.ExecutionStatistics)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::tools::protos::ResourceUsage* resource_usage_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_execution_5fstatistics_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ResourceUsage

// int64 utime_sec = 1;
inline void ResourceUsage::clear_utime_sec() {
  utime_sec_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 ResourceUsage::_internal_utime_sec() const {
  return utime_sec_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 ResourceUsage::utime_sec() const {
  // @@protoc_insertion_point(field_get:tools.protos.ResourceUsage.utime_sec)
  return _internal_utime_sec();
}
inline void ResourceUsage::_internal_set_utime_sec(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  utime_sec_ = value;
}
inline void ResourceUsage::set_utime_sec(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_utime_sec(value);
  // @@protoc_insertion_point(field_set:tools.protos.ResourceUsage.utime_sec)
}

// int64 utime_usec = 2;
inline void ResourceUsage::clear_utime_usec() {
  utime_usec_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 ResourceUsage::_internal_utime_usec() const {
  return utime_usec_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 ResourceUsage::utime_usec() const {
  // @@protoc_insertion_point(field_get:tools.protos.ResourceUsage.utime_usec)
  return _internal_utime_usec();
}
inline void ResourceUsage::_internal_set_utime_usec(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  utime_usec_ = value;
}
inline void ResourceUsage::set_utime_usec(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_utime_usec(value);
  // @@protoc_insertion_point(field_set:tools.protos.ResourceUsage.utime_usec)
}

// int64 stime_sec = 3;
inline void ResourceUsage::clear_stime_sec() {
  stime_sec_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 ResourceUsage::_internal_stime_sec() const {
  return stime_sec_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 ResourceUsage::stime_sec() const {
  // @@protoc_insertion_point(field_get:tools.protos.ResourceUsage.stime_sec)
  return _internal_stime_sec();
}
inline void ResourceUsage::_internal_set_stime_sec(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  stime_sec_ = value;
}
inline void ResourceUsage::set_stime_sec(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_stime_sec(value);
  // @@protoc_insertion_point(field_set:tools.protos.ResourceUsage.stime_sec)
}

// int64 stime_usec = 4;
inline void ResourceUsage::clear_stime_usec() {
  stime_usec_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 ResourceUsage::_internal_stime_usec() const {
  return stime_usec_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 ResourceUsage::stime_usec() const {
  // @@protoc_insertion_point(field_get:tools.protos.ResourceUsage.stime_usec)
  return _internal_stime_usec();
}
inline void ResourceUsage::_internal_set_stime_usec(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  stime_usec_ = value;
}
inline void ResourceUsage::set_stime_usec(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_stime_usec(value);
  // @@protoc_insertion_point(field_set:tools.protos.ResourceUsage.stime_usec)
}

// int64 maxrss = 5;
inline void ResourceUsage::clear_maxrss() {
  maxrss_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 ResourceUsage::_internal_maxrss() const {
  return maxrss_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 ResourceUsage::maxrss() const {
  // @@protoc_insertion_point(field_get:tools.protos.ResourceUsage.maxrss)
  return _internal_maxrss();
}
inline void ResourceUsage::_internal_set_maxrss(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  maxrss_ = value;
}
inline void ResourceUsage::set_maxrss(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_maxrss(value);
  // @@protoc_insertion_point(field_set:tools.protos.ResourceUsage.maxrss)
}

// int64 ixrss = 6;
inline void ResourceUsage::clear_ixrss() {
  ixrss_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 ResourceUsage::_internal_ixrss() const {
  return ixrss_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 ResourceUsage::ixrss() const {
  // @@protoc_insertion_point(field_get:tools.protos.ResourceUsage.ixrss)
  return _internal_ixrss();
}
inline void ResourceUsage::_internal_set_ixrss(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  ixrss_ = value;
}
inline void ResourceUsage::set_ixrss(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_ixrss(value);
  // @@protoc_insertion_point(field_set:tools.protos.ResourceUsage.ixrss)
}

// int64 idrss = 7;
inline void ResourceUsage::clear_idrss() {
  idrss_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 ResourceUsage::_internal_idrss() const {
  return idrss_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 ResourceUsage::idrss() const {
  // @@protoc_insertion_point(field_get:tools.protos.ResourceUsage.idrss)
  return _internal_idrss();
}
inline void ResourceUsage::_internal_set_idrss(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  idrss_ = value;
}
inline void ResourceUsage::set_idrss(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_idrss(value);
  // @@protoc_insertion_point(field_set:tools.protos.ResourceUsage.idrss)
}

// int64 isrss = 8;
inline void ResourceUsage::clear_isrss() {
  isrss_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 ResourceUsage::_internal_isrss() const {
  return isrss_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 ResourceUsage::isrss() const {
  // @@protoc_insertion_point(field_get:tools.protos.ResourceUsage.isrss)
  return _internal_isrss();
}
inline void ResourceUsage::_internal_set_isrss(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  isrss_ = value;
}
inline void ResourceUsage::set_isrss(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_isrss(value);
  // @@protoc_insertion_point(field_set:tools.protos.ResourceUsage.isrss)
}

// int64 minflt = 9;
inline void ResourceUsage::clear_minflt() {
  minflt_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 ResourceUsage::_internal_minflt() const {
  return minflt_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 ResourceUsage::minflt() const {
  // @@protoc_insertion_point(field_get:tools.protos.ResourceUsage.minflt)
  return _internal_minflt();
}
inline void ResourceUsage::_internal_set_minflt(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  minflt_ = value;
}
inline void ResourceUsage::set_minflt(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_minflt(value);
  // @@protoc_insertion_point(field_set:tools.protos.ResourceUsage.minflt)
}

// int64 majflt = 10;
inline void ResourceUsage::clear_majflt() {
  majflt_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 ResourceUsage::_internal_majflt() const {
  return majflt_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 ResourceUsage::majflt() const {
  // @@protoc_insertion_point(field_get:tools.protos.ResourceUsage.majflt)
  return _internal_majflt();
}
inline void ResourceUsage::_internal_set_majflt(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  majflt_ = value;
}
inline void ResourceUsage::set_majflt(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_majflt(value);
  // @@protoc_insertion_point(field_set:tools.protos.ResourceUsage.majflt)
}

// int64 nswap = 11;
inline void ResourceUsage::clear_nswap() {
  nswap_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 ResourceUsage::_internal_nswap() const {
  return nswap_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 ResourceUsage::nswap() const {
  // @@protoc_insertion_point(field_get:tools.protos.ResourceUsage.nswap)
  return _internal_nswap();
}
inline void ResourceUsage::_internal_set_nswap(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  nswap_ = value;
}
inline void ResourceUsage::set_nswap(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_nswap(value);
  // @@protoc_insertion_point(field_set:tools.protos.ResourceUsage.nswap)
}

// int64 inblock = 12;
inline void ResourceUsage::clear_inblock() {
  inblock_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 ResourceUsage::_internal_inblock() const {
  return inblock_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 ResourceUsage::inblock() const {
  // @@protoc_insertion_point(field_get:tools.protos.ResourceUsage.inblock)
  return _internal_inblock();
}
inline void ResourceUsage::_internal_set_inblock(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  inblock_ = value;
}
inline void ResourceUsage::set_inblock(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_inblock(value);
  // @@protoc_insertion_point(field_set:tools.protos.ResourceUsage.inblock)
}

// int64 oublock = 13;
inline void ResourceUsage::clear_oublock() {
  oublock_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 ResourceUsage::_internal_oublock() const {
  return oublock_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 ResourceUsage::oublock() const {
  // @@protoc_insertion_point(field_get:tools.protos.ResourceUsage.oublock)
  return _internal_oublock();
}
inline void ResourceUsage::_internal_set_oublock(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  oublock_ = value;
}
inline void ResourceUsage::set_oublock(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_oublock(value);
  // @@protoc_insertion_point(field_set:tools.protos.ResourceUsage.oublock)
}

// int64 msgsnd = 14;
inline void ResourceUsage::clear_msgsnd() {
  msgsnd_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 ResourceUsage::_internal_msgsnd() const {
  return msgsnd_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 ResourceUsage::msgsnd() const {
  // @@protoc_insertion_point(field_get:tools.protos.ResourceUsage.msgsnd)
  return _internal_msgsnd();
}
inline void ResourceUsage::_internal_set_msgsnd(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  msgsnd_ = value;
}
inline void ResourceUsage::set_msgsnd(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_msgsnd(value);
  // @@protoc_insertion_point(field_set:tools.protos.ResourceUsage.msgsnd)
}

// int64 msgrcv = 15;
inline void ResourceUsage::clear_msgrcv() {
  msgrcv_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 ResourceUsage::_internal_msgrcv() const {
  return msgrcv_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 ResourceUsage::msgrcv() const {
  // @@protoc_insertion_point(field_get:tools.protos.ResourceUsage.msgrcv)
  return _internal_msgrcv();
}
inline void ResourceUsage::_internal_set_msgrcv(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  msgrcv_ = value;
}
inline void ResourceUsage::set_msgrcv(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_msgrcv(value);
  // @@protoc_insertion_point(field_set:tools.protos.ResourceUsage.msgrcv)
}

// int64 nsignals = 16;
inline void ResourceUsage::clear_nsignals() {
  nsignals_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 ResourceUsage::_internal_nsignals() const {
  return nsignals_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 ResourceUsage::nsignals() const {
  // @@protoc_insertion_point(field_get:tools.protos.ResourceUsage.nsignals)
  return _internal_nsignals();
}
inline void ResourceUsage::_internal_set_nsignals(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  nsignals_ = value;
}
inline void ResourceUsage::set_nsignals(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_nsignals(value);
  // @@protoc_insertion_point(field_set:tools.protos.ResourceUsage.nsignals)
}

// int64 nvcsw = 17;
inline void ResourceUsage::clear_nvcsw() {
  nvcsw_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 ResourceUsage::_internal_nvcsw() const {
  return nvcsw_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 ResourceUsage::nvcsw() const {
  // @@protoc_insertion_point(field_get:tools.protos.ResourceUsage.nvcsw)
  return _internal_nvcsw();
}
inline void ResourceUsage::_internal_set_nvcsw(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  nvcsw_ = value;
}
inline void ResourceUsage::set_nvcsw(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_nvcsw(value);
  // @@protoc_insertion_point(field_set:tools.protos.ResourceUsage.nvcsw)
}

// int64 nivcsw = 18;
inline void ResourceUsage::clear_nivcsw() {
  nivcsw_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 ResourceUsage::_internal_nivcsw() const {
  return nivcsw_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 ResourceUsage::nivcsw() const {
  // @@protoc_insertion_point(field_get:tools.protos.ResourceUsage.nivcsw)
  return _internal_nivcsw();
}
inline void ResourceUsage::_internal_set_nivcsw(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  nivcsw_ = value;
}
inline void ResourceUsage::set_nivcsw(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_nivcsw(value);
  // @@protoc_insertion_point(field_set:tools.protos.ResourceUsage.nivcsw)
}

// -------------------------------------------------------------------

// ExecutionStatistics

// .tools.protos.ResourceUsage resource_usage = 1;
inline bool ExecutionStatistics::_internal_has_resource_usage() const {
  return this != internal_default_instance() && resource_usage_ != nullptr;
}
inline bool ExecutionStatistics::has_resource_usage() const {
  return _internal_has_resource_usage();
}
inline void ExecutionStatistics::clear_resource_usage() {
  if (GetArena() == nullptr && resource_usage_ != nullptr) {
    delete resource_usage_;
  }
  resource_usage_ = nullptr;
}
inline const ::tools::protos::ResourceUsage& ExecutionStatistics::_internal_resource_usage() const {
  const ::tools::protos::ResourceUsage* p = resource_usage_;
  return p != nullptr ? *p : *reinterpret_cast<const ::tools::protos::ResourceUsage*>(
      &::tools::protos::_ResourceUsage_default_instance_);
}
inline const ::tools::protos::ResourceUsage& ExecutionStatistics::resource_usage() const {
  // @@protoc_insertion_point(field_get:tools.protos.ExecutionStatistics.resource_usage)
  return _internal_resource_usage();
}
inline void ExecutionStatistics::unsafe_arena_set_allocated_resource_usage(
    ::tools::protos::ResourceUsage* resource_usage) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(resource_usage_);
  }
  resource_usage_ = resource_usage;
  if (resource_usage) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:tools.protos.ExecutionStatistics.resource_usage)
}
inline ::tools::protos::ResourceUsage* ExecutionStatistics::release_resource_usage() {
  auto temp = unsafe_arena_release_resource_usage();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::tools::protos::ResourceUsage* ExecutionStatistics::unsafe_arena_release_resource_usage() {
  // @@protoc_insertion_point(field_release:tools.protos.ExecutionStatistics.resource_usage)
  
  ::tools::protos::ResourceUsage* temp = resource_usage_;
  resource_usage_ = nullptr;
  return temp;
}
inline ::tools::protos::ResourceUsage* ExecutionStatistics::_internal_mutable_resource_usage() {
  
  if (resource_usage_ == nullptr) {
    auto* p = CreateMaybeMessage<::tools::protos::ResourceUsage>(GetArena());
    resource_usage_ = p;
  }
  return resource_usage_;
}
inline ::tools::protos::ResourceUsage* ExecutionStatistics::mutable_resource_usage() {
  // @@protoc_insertion_point(field_mutable:tools.protos.ExecutionStatistics.resource_usage)
  return _internal_mutable_resource_usage();
}
inline void ExecutionStatistics::set_allocated_resource_usage(::tools::protos::ResourceUsage* resource_usage) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete resource_usage_;
  }
  if (resource_usage) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(resource_usage);
    if (message_arena != submessage_arena) {
      resource_usage = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, resource_usage, submessage_arena);
    }
    
  } else {
    
  }
  resource_usage_ = resource_usage;
  // @@protoc_insertion_point(field_set_allocated:tools.protos.ExecutionStatistics.resource_usage)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace protos
}  // namespace tools

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_execution_5fstatistics_2eproto
