FROM ubuntu:24.04

RUN apt-get update && \
    apt-get install -y \
        xfsprogs \
        sudo \
        wget \
        vim \
        make \
        clang \
        gcc \
        g++ \
        binutils \
        libc6-dev \
        which \
        iptables \
        python3 \
        python3-pip \
	python3-requests \
        ca-certificates && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

RUN groupadd -r app && useradd --no-log-init -r -g app app

WORKDIR /app
RUN mkdir /app/mini-sandbox
ARG V=dist
COPY ${V}/ /app/

COPY ./ /app/mini-sandbox
RUN chown -R app:app /app
RUN /app/mini-sandbox/clean.sh

ENV MINI_SANDBOX_DOCKER_PRIVILEGED=1
ENV PATH="/app/release/bin:$PATH"
ENV LD_LIBRARY_PATH="/app/release/lib"
ENV PYTHON=python3
ENV PYTHONPATH="/app/release/python/"
ENV PACKAGE_DIR="/app/release"
ENV LDFLAGS="-lstdc++fs"
ENV WORKSPACE="/app/mini-sandbox"
ENV LANDLOCK_TEST=1

USER app
ENTRYPOINT ["sh", "-c", "set -e && cd /app/mini-sandbox/mini_sandbox/utils/test/ && export HOME=/app && ./test_all.sh"]
