// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: execution_statistics.proto

#include "execution_statistics.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_execution_5fstatistics_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_ResourceUsage_execution_5fstatistics_2eproto;
namespace tools {
namespace protos {
class ResourceUsageDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<ResourceUsage> _instance;
} _ResourceUsage_default_instance_;
class ExecutionStatisticsDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<ExecutionStatistics> _instance;
} _ExecutionStatistics_default_instance_;
}  // namespace protos
}  // namespace tools
static void InitDefaultsscc_info_ExecutionStatistics_execution_5fstatistics_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::tools::protos::_ExecutionStatistics_default_instance_;
    new (ptr) ::tools::protos::ExecutionStatistics();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::tools::protos::ExecutionStatistics::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_ExecutionStatistics_execution_5fstatistics_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_ExecutionStatistics_execution_5fstatistics_2eproto}, {
      &scc_info_ResourceUsage_execution_5fstatistics_2eproto.base,}};

static void InitDefaultsscc_info_ResourceUsage_execution_5fstatistics_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::tools::protos::_ResourceUsage_default_instance_;
    new (ptr) ::tools::protos::ResourceUsage();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::tools::protos::ResourceUsage::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_ResourceUsage_execution_5fstatistics_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_ResourceUsage_execution_5fstatistics_2eproto}, {}};

namespace tools {
namespace protos {

// ===================================================================

void ResourceUsage::InitAsDefaultInstance() {
}
class ResourceUsage::_Internal {
 public:
};

ResourceUsage::ResourceUsage(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:tools.protos.ResourceUsage)
}
ResourceUsage::ResourceUsage(const ResourceUsage& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite() {
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  ::memcpy(&utime_sec_, &from.utime_sec_,
    static_cast<size_t>(reinterpret_cast<char*>(&nivcsw_) -
    reinterpret_cast<char*>(&utime_sec_)) + sizeof(nivcsw_));
  // @@protoc_insertion_point(copy_constructor:tools.protos.ResourceUsage)
}

void ResourceUsage::SharedCtor() {
  ::memset(&utime_sec_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&nivcsw_) -
      reinterpret_cast<char*>(&utime_sec_)) + sizeof(nivcsw_));
}

ResourceUsage::~ResourceUsage() {
  // @@protoc_insertion_point(destructor:tools.protos.ResourceUsage)
  SharedDtor();
  _internal_metadata_.Delete<std::string>();
}

void ResourceUsage::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void ResourceUsage::ArenaDtor(void* object) {
  ResourceUsage* _this = reinterpret_cast< ResourceUsage* >(object);
  (void)_this;
}
void ResourceUsage::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void ResourceUsage::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ResourceUsage& ResourceUsage::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_ResourceUsage_execution_5fstatistics_2eproto.base);
  return *internal_default_instance();
}


void ResourceUsage::Clear() {
// @@protoc_insertion_point(message_clear_start:tools.protos.ResourceUsage)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&utime_sec_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&nivcsw_) -
      reinterpret_cast<char*>(&utime_sec_)) + sizeof(nivcsw_));
  _internal_metadata_.Clear<std::string>();
}

const char* ResourceUsage::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // int64 utime_sec = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          utime_sec_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int64 utime_usec = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          utime_usec_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int64 stime_sec = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          stime_sec_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int64 stime_usec = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 32)) {
          stime_usec_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int64 maxrss = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 40)) {
          maxrss_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int64 ixrss = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 48)) {
          ixrss_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int64 idrss = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 56)) {
          idrss_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int64 isrss = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 64)) {
          isrss_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int64 minflt = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 72)) {
          minflt_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int64 majflt = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 80)) {
          majflt_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int64 nswap = 11;
      case 11:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 88)) {
          nswap_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int64 inblock = 12;
      case 12:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 96)) {
          inblock_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int64 oublock = 13;
      case 13:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 104)) {
          oublock_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int64 msgsnd = 14;
      case 14:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 112)) {
          msgsnd_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int64 msgrcv = 15;
      case 15:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 120)) {
          msgrcv_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int64 nsignals = 16;
      case 16:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 128)) {
          nsignals_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int64 nvcsw = 17;
      case 17:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 136)) {
          nvcsw_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int64 nivcsw = 18;
      case 18:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 144)) {
          nivcsw_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<std::string>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* ResourceUsage::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:tools.protos.ResourceUsage)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 utime_sec = 1;
  if (this->utime_sec() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt64ToArray(1, this->_internal_utime_sec(), target);
  }

  // int64 utime_usec = 2;
  if (this->utime_usec() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt64ToArray(2, this->_internal_utime_usec(), target);
  }

  // int64 stime_sec = 3;
  if (this->stime_sec() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt64ToArray(3, this->_internal_stime_sec(), target);
  }

  // int64 stime_usec = 4;
  if (this->stime_usec() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt64ToArray(4, this->_internal_stime_usec(), target);
  }

  // int64 maxrss = 5;
  if (this->maxrss() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt64ToArray(5, this->_internal_maxrss(), target);
  }

  // int64 ixrss = 6;
  if (this->ixrss() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt64ToArray(6, this->_internal_ixrss(), target);
  }

  // int64 idrss = 7;
  if (this->idrss() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt64ToArray(7, this->_internal_idrss(), target);
  }

  // int64 isrss = 8;
  if (this->isrss() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt64ToArray(8, this->_internal_isrss(), target);
  }

  // int64 minflt = 9;
  if (this->minflt() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt64ToArray(9, this->_internal_minflt(), target);
  }

  // int64 majflt = 10;
  if (this->majflt() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt64ToArray(10, this->_internal_majflt(), target);
  }

  // int64 nswap = 11;
  if (this->nswap() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt64ToArray(11, this->_internal_nswap(), target);
  }

  // int64 inblock = 12;
  if (this->inblock() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt64ToArray(12, this->_internal_inblock(), target);
  }

  // int64 oublock = 13;
  if (this->oublock() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt64ToArray(13, this->_internal_oublock(), target);
  }

  // int64 msgsnd = 14;
  if (this->msgsnd() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt64ToArray(14, this->_internal_msgsnd(), target);
  }

  // int64 msgrcv = 15;
  if (this->msgrcv() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt64ToArray(15, this->_internal_msgrcv(), target);
  }

  // int64 nsignals = 16;
  if (this->nsignals() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt64ToArray(16, this->_internal_nsignals(), target);
  }

  // int64 nvcsw = 17;
  if (this->nvcsw() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt64ToArray(17, this->_internal_nvcsw(), target);
  }

  // int64 nivcsw = 18;
  if (this->nivcsw() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt64ToArray(18, this->_internal_nivcsw(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:tools.protos.ResourceUsage)
  return target;
}

size_t ResourceUsage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tools.protos.ResourceUsage)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int64 utime_sec = 1;
  if (this->utime_sec() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int64Size(
        this->_internal_utime_sec());
  }

  // int64 utime_usec = 2;
  if (this->utime_usec() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int64Size(
        this->_internal_utime_usec());
  }

  // int64 stime_sec = 3;
  if (this->stime_sec() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int64Size(
        this->_internal_stime_sec());
  }

  // int64 stime_usec = 4;
  if (this->stime_usec() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int64Size(
        this->_internal_stime_usec());
  }

  // int64 maxrss = 5;
  if (this->maxrss() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int64Size(
        this->_internal_maxrss());
  }

  // int64 ixrss = 6;
  if (this->ixrss() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int64Size(
        this->_internal_ixrss());
  }

  // int64 idrss = 7;
  if (this->idrss() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int64Size(
        this->_internal_idrss());
  }

  // int64 isrss = 8;
  if (this->isrss() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int64Size(
        this->_internal_isrss());
  }

  // int64 minflt = 9;
  if (this->minflt() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int64Size(
        this->_internal_minflt());
  }

  // int64 majflt = 10;
  if (this->majflt() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int64Size(
        this->_internal_majflt());
  }

  // int64 nswap = 11;
  if (this->nswap() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int64Size(
        this->_internal_nswap());
  }

  // int64 inblock = 12;
  if (this->inblock() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int64Size(
        this->_internal_inblock());
  }

  // int64 oublock = 13;
  if (this->oublock() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int64Size(
        this->_internal_oublock());
  }

  // int64 msgsnd = 14;
  if (this->msgsnd() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int64Size(
        this->_internal_msgsnd());
  }

  // int64 msgrcv = 15;
  if (this->msgrcv() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int64Size(
        this->_internal_msgrcv());
  }

  // int64 nsignals = 16;
  if (this->nsignals() != 0) {
    total_size += 2 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int64Size(
        this->_internal_nsignals());
  }

  // int64 nvcsw = 17;
  if (this->nvcsw() != 0) {
    total_size += 2 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int64Size(
        this->_internal_nvcsw());
  }

  // int64 nivcsw = 18;
  if (this->nivcsw() != 0) {
    total_size += 2 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int64Size(
        this->_internal_nivcsw());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ResourceUsage::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::PROTOBUF_NAMESPACE_ID::internal::DownCast<const ResourceUsage*>(
      &from));
}

void ResourceUsage::MergeFrom(const ResourceUsage& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:tools.protos.ResourceUsage)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.utime_sec() != 0) {
    _internal_set_utime_sec(from._internal_utime_sec());
  }
  if (from.utime_usec() != 0) {
    _internal_set_utime_usec(from._internal_utime_usec());
  }
  if (from.stime_sec() != 0) {
    _internal_set_stime_sec(from._internal_stime_sec());
  }
  if (from.stime_usec() != 0) {
    _internal_set_stime_usec(from._internal_stime_usec());
  }
  if (from.maxrss() != 0) {
    _internal_set_maxrss(from._internal_maxrss());
  }
  if (from.ixrss() != 0) {
    _internal_set_ixrss(from._internal_ixrss());
  }
  if (from.idrss() != 0) {
    _internal_set_idrss(from._internal_idrss());
  }
  if (from.isrss() != 0) {
    _internal_set_isrss(from._internal_isrss());
  }
  if (from.minflt() != 0) {
    _internal_set_minflt(from._internal_minflt());
  }
  if (from.majflt() != 0) {
    _internal_set_majflt(from._internal_majflt());
  }
  if (from.nswap() != 0) {
    _internal_set_nswap(from._internal_nswap());
  }
  if (from.inblock() != 0) {
    _internal_set_inblock(from._internal_inblock());
  }
  if (from.oublock() != 0) {
    _internal_set_oublock(from._internal_oublock());
  }
  if (from.msgsnd() != 0) {
    _internal_set_msgsnd(from._internal_msgsnd());
  }
  if (from.msgrcv() != 0) {
    _internal_set_msgrcv(from._internal_msgrcv());
  }
  if (from.nsignals() != 0) {
    _internal_set_nsignals(from._internal_nsignals());
  }
  if (from.nvcsw() != 0) {
    _internal_set_nvcsw(from._internal_nvcsw());
  }
  if (from.nivcsw() != 0) {
    _internal_set_nivcsw(from._internal_nivcsw());
  }
}

void ResourceUsage::CopyFrom(const ResourceUsage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tools.protos.ResourceUsage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ResourceUsage::IsInitialized() const {
  return true;
}

void ResourceUsage::InternalSwap(ResourceUsage* other) {
  using std::swap;
  _internal_metadata_.Swap<std::string>(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ResourceUsage, nivcsw_)
      + sizeof(ResourceUsage::nivcsw_)
      - PROTOBUF_FIELD_OFFSET(ResourceUsage, utime_sec_)>(
          reinterpret_cast<char*>(&utime_sec_),
          reinterpret_cast<char*>(&other->utime_sec_));
}

std::string ResourceUsage::GetTypeName() const {
  return "tools.protos.ResourceUsage";
}


// ===================================================================

void ExecutionStatistics::InitAsDefaultInstance() {
  ::tools::protos::_ExecutionStatistics_default_instance_._instance.get_mutable()->resource_usage_ = const_cast< ::tools::protos::ResourceUsage*>(
      ::tools::protos::ResourceUsage::internal_default_instance());
}
class ExecutionStatistics::_Internal {
 public:
  static const ::tools::protos::ResourceUsage& resource_usage(const ExecutionStatistics* msg);
};

const ::tools::protos::ResourceUsage&
ExecutionStatistics::_Internal::resource_usage(const ExecutionStatistics* msg) {
  return *msg->resource_usage_;
}
ExecutionStatistics::ExecutionStatistics(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:tools.protos.ExecutionStatistics)
}
ExecutionStatistics::ExecutionStatistics(const ExecutionStatistics& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite() {
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  if (from._internal_has_resource_usage()) {
    resource_usage_ = new ::tools::protos::ResourceUsage(*from.resource_usage_);
  } else {
    resource_usage_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:tools.protos.ExecutionStatistics)
}

void ExecutionStatistics::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_ExecutionStatistics_execution_5fstatistics_2eproto.base);
  resource_usage_ = nullptr;
}

ExecutionStatistics::~ExecutionStatistics() {
  // @@protoc_insertion_point(destructor:tools.protos.ExecutionStatistics)
  SharedDtor();
  _internal_metadata_.Delete<std::string>();
}

void ExecutionStatistics::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  if (this != internal_default_instance()) delete resource_usage_;
}

void ExecutionStatistics::ArenaDtor(void* object) {
  ExecutionStatistics* _this = reinterpret_cast< ExecutionStatistics* >(object);
  (void)_this;
}
void ExecutionStatistics::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void ExecutionStatistics::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ExecutionStatistics& ExecutionStatistics::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_ExecutionStatistics_execution_5fstatistics_2eproto.base);
  return *internal_default_instance();
}


void ExecutionStatistics::Clear() {
// @@protoc_insertion_point(message_clear_start:tools.protos.ExecutionStatistics)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArena() == nullptr && resource_usage_ != nullptr) {
    delete resource_usage_;
  }
  resource_usage_ = nullptr;
  _internal_metadata_.Clear<std::string>();
}

const char* ExecutionStatistics::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // .tools.protos.ResourceUsage resource_usage = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_resource_usage(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<std::string>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* ExecutionStatistics::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:tools.protos.ExecutionStatistics)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .tools.protos.ResourceUsage resource_usage = 1;
  if (this->has_resource_usage()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        1, _Internal::resource_usage(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:tools.protos.ExecutionStatistics)
  return target;
}

size_t ExecutionStatistics::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tools.protos.ExecutionStatistics)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .tools.protos.ResourceUsage resource_usage = 1;
  if (this->has_resource_usage()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *resource_usage_);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ExecutionStatistics::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::PROTOBUF_NAMESPACE_ID::internal::DownCast<const ExecutionStatistics*>(
      &from));
}

void ExecutionStatistics::MergeFrom(const ExecutionStatistics& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:tools.protos.ExecutionStatistics)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_resource_usage()) {
    _internal_mutable_resource_usage()->::tools::protos::ResourceUsage::MergeFrom(from._internal_resource_usage());
  }
}

void ExecutionStatistics::CopyFrom(const ExecutionStatistics& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tools.protos.ExecutionStatistics)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ExecutionStatistics::IsInitialized() const {
  return true;
}

void ExecutionStatistics::InternalSwap(ExecutionStatistics* other) {
  using std::swap;
  _internal_metadata_.Swap<std::string>(&other->_internal_metadata_);
  swap(resource_usage_, other->resource_usage_);
}

std::string ExecutionStatistics::GetTypeName() const {
  return "tools.protos.ExecutionStatistics";
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace protos
}  // namespace tools
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::tools::protos::ResourceUsage* Arena::CreateMaybeMessage< ::tools::protos::ResourceUsage >(Arena* arena) {
  return Arena::CreateMessageInternal< ::tools::protos::ResourceUsage >(arena);
}
template<> PROTOBUF_NOINLINE ::tools::protos::ExecutionStatistics* Arena::CreateMaybeMessage< ::tools::protos::ExecutionStatistics >(Arena* arena) {
  return Arena::CreateMessageInternal< ::tools::protos::ExecutionStatistics >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
